apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-configserver
spec:
  serviceName: "mongodb-configserver"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-configserver
  template:
    metadata:
      labels:
        app: mongodb-configserver
        role: configsvr
    spec:
      containers:
      - name: mongodb-configserver
        image: mongo:6.0
        command:
          - mongod
          - "--bind_ip_all"
          - "--configsvr"
          - "--replSet"
          - "configReplSet"
          - "--port"
          - "27019"
        ports:
          - containerPort: 27019
        volumeMounts:
          - name: mongodb-configserver-data
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-configserver-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard   
        resources:
          requests:
            storage: 1Gi
