apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard1
spec:
  selector:
    app: mongodb-shard1
  clusterIP: None
  ports:
  - port: 27018
    targetPort: 27018
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard2
spec:
  selector:
    app: mongodb-shard2
  clusterIP: None
  ports:
  - port: 27018
    targetPort: 27018