apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-shard1
spec:
  serviceName: "mongodb-shard1"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-shard1
  template:
    metadata:
      labels:
        app: mongodb-shard1
        role: shardsvr
    spec:
      containers:
      - name: mongodb-shard1
        image: mongo:6.0
        command:
        - mongod
        - "--bind_ip_all"
        - "--shardsvr"
        - "--replSet"
        - "shard1RepSet"
        - "--port"
        - "27018"
        volumeMounts:
        - name: mongodb-shard1-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-shard1-data
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # No storageClassName specified - will use the default
      resources:
        requests:
          storage: 2Gi