apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-mongos
  template:
    metadata:
      labels:
        app: mongodb-mongos
    spec:
      containers:
      - name: mongodb-mongos
        image: mongo:6.0
        command:
        - mongos
        - "--bind_ip_all"
        - "--port"
        - "27017"
        - "--configdb"
        - "configReplSet/mongodb-configserver-0.mongodb-configserver.default.svc.cluster.local:27019,mongodb-configserver-1.mongodb-configserver.default.svc.cluster.local:27019,mongodb-configserver-2.mongodb-configserver.default.svc.cluster.local:27019"
        ports:
        - containerPort: 27017