apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: rs0
    sharding:
      clusterRole: shardsvr
  mongodb-configserver.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: configReplSet
    sharding:
      clusterRole: configsvr
  mongodb-mongos.conf: |
    net:
      bindIp: 0.0.0.0
    sharding:
      configDB: configReplSet/mongodb-configserver-0.mongodb-configserver.default.svc.cluster.local:27019,mongodb-configserver-1.mongodb-configserver.default.svc.cluster.local:27019,mongodb-configserver-2.mongodb-configserver.default.svc.cluster.local:27019