apiVersion: v1
kind: Pod
metadata:
  name: ycsb
spec:
  restartPolicy: Always
  containers:
    - name: ycsb-container
      image: ycsb-image
      imagePullPolicy: Never
      command: [ "bash" ]
      stdin: true
      tty: true
