kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # Name of the ClusterRole
  name: statefulset-scaler
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # Name of the ClusterRoleBinding
  name: default-statefulset-scaler-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: statefulset-scaler
  apiGroup: rbac.authorization.k8s.io
